// Copyright 2011-2012 James Michael Callahan
// See LICENSE-2.0 file for licensing information.

package org.scalagfx.math

//--------------------------------------------------------------------------------------------------
//   V E C T O R   3 D                                                                     
//--------------------------------------------------------------------------------------------------

//--------------------------------------------------------------------------------------------------
//  Supported Operations:                                                      
//                                                          
//    V + S -> V      V - S -> V      V * S -> V      V / S -> V           
//
//    V + V -> V      V - V -> V      V * V -> V      V / V -> V 
//                                                                                       
//  S = Scalar(Double), V = Vector(Vector3d)                           
//--------------------------------------------------------------------------------------------------

/** Companion object for Vector3d. */
object Vector3d 
{
  //------------------------------------------------------------------------------------------------
  //   C R E A T I O N                                                                     
  //------------------------------------------------------------------------------------------------

  /** Create a new vector with all components set to the given value. */
  def apply(s: Double) = 
    new Vector3d(s, s, s) 

  /** Create a new vector from components. */
  def apply(x: Double, y: Double, z: Double) = 
    new Vector3d(x, y, z)


  /** A unit length vector along the X-axis. */ 
  val unitX: Vector3d = 
    Vector3d(1.0, 0.0, 0.0)

  /** A unit length vector along the Y-axis. */ 
  val unitY: Vector3d = 
    Vector3d(0.0, 1.0, 0.0) 

  /** A unit length vector along the Z-axis. */ 
  val unitZ: Vector3d = 
    Vector3d(0.0, 0.0, 1.0) 


  //------------------------------------------------------------------------------------------------
  //   C O M P A R I S O N                                                                  
  //------------------------------------------------------------------------------------------------

  /** The component-wise comparison of whether two vectors are within a given epsilon. */ 
  def equiv(a: Vector3d, b: Vector3d, epsilon: Double): Boolean = 
    a.equiv(b, epsilon) 
  
  /** The component-wise comparison of whether two vectors are within a type specific
    * epsilon. */ 
  def equiv(a: Vector3d, b: Vector3d): Boolean = 
    (a equiv b)
  
  /** The component-wise minimum of two vectors. */
  def min(a: Vector3d, b: Vector3d): Vector3d = 
    compwise(a, b, scala.math.min(_, _)) 
  
  /** The component-wise maximum of two vectors. */
  def max(a: Vector3d, b: Vector3d): Vector3d = 
    compwise(a, b, scala.math.max(_, _)) 
  			
  
  //------------------------------------------------------------------------------------------------
  //   I N T E R P O L A T I O N                                                           
  //------------------------------------------------------------------------------------------------

  /** Linearly interpolate between two vectors. */
  def lerp(a: Vector3d, b: Vector3d, t: Double): Vector3d = 
    compwise(a, b, Scalar.lerp(_, _, t)) 
  
  /** Smooth-step interpolate between two vectors. */
  def smoothlerp(a: Vector3d, b: Vector3d, t: Double): Vector3d = 
    compwise(a, b, Scalar.smoothlerp(_, _, t)) 


  //------------------------------------------------------------------------------------------------
  //   U T I L I T Y                                                                        
  //------------------------------------------------------------------------------------------------

  /** Create a vector who's components are generated by applying the given binary operator
    * to each of the corresponding components of the given two vectors. */ 
  def compwise(a: Vector3d, b: Vector3d, f: (Double, Double) => Double): Vector3d = 
    Vector3d(f(a.x, b.x), f(a.y, b.y), f(a.z, b.z))
}

/** An immutable 3-dimensional vector of Double element type used to represent vectors
  * for use in computational geometry applications. */ 
class Vector3d(val x: Double, val y: Double, val z: Double) extends Vector3dLike
{
  type Self = Vector3d
  
  //------------------------------------------------------------------------------------------------
  //   C O M P O N E N T   O P S                                                            
  //------------------------------------------------------------------------------------------------

  /** A copy of this vector in which the X component has been replaced with the given
    * value. */ 
  def newX(v: Double): Vector3d = 
    Vector3d(v, y, z)
  
  /** A copy of this vector in which the Y component has been replaced with the given
    * value. */ 
  def newY(v: Double): Vector3d = 
    Vector3d(x, v, z)
  
  /** A copy of this vector in which the Z component has been replaced with the given
    * value. */ 
  def newZ(v: Double): Vector3d = 
    Vector3d(x, y, v)
  
  /** A copy of this vector in which the component with the given index as been replaced. */
  def newComp(i: Int, v: Double) = 
    i match {
      case 0 => Vector3d(v, y, z)
      case 1 => Vector3d(x, v, z)
      case 2 => Vector3d(x, y, v)  
      case _ => throw new IllegalArgumentException("Invalid index (" + i + ")!")
    }

  
  //------------------------------------------------------------------------------------------------
  //   U N A R Y   O P S                                                                    
  //------------------------------------------------------------------------------------------------

  /** A vector of identical magnitude but opposite direction. */
  def negated: Vector3d = Vector3d(-x, -y, -z)

  /** The length (magnitude) of this vector squared. */
  def lengthSq: Double = dot(this)

  /** The length (magnitude) of this vector. */
  def length: Double = scala.math.sqrt(lengthSq)

  /** A vector of identical direction but unit length. */
  def normalized: Self = this * (1.0 / length) 

  /** A 2-dimensional vector in which XY components of this vector have been divided by Z. */ 
  def homogenized: Vector2d = 
    if(!Scalar.equiv(z, 0.0)) Vector2d(x/z, y/z)
    else throw new UnsupportedOperationException("The Z component of this vector was zero!")


  					    
  //------------------------------------------------------------------------------------------------
  //   O P E R A T O R S                                                                    
  //------------------------------------------------------------------------------------------------

  /** The addition of a scalar value to all components of this vector. */ 
  def + (scalar: Double): Vector3d = Vector3d(x+scalar, y+scalar, z+scalar) 

  /** The component-wise addition of this vector with another vector. */ 
  def + (that: Vector3d): Vector3d = Vector3d(x+that.x, y+that.y, z+that.z)
  

  /** The subtraction of a scalar value from all components of this vector. */ 
  def - (scalar: Double): Vector3d = Vector3d(x-scalar, y-scalar, z-scalar)
  
  /** The component-wise subtraction of another vector from this vector. */ 
  def - (that: Vector3d): Vector3d = Vector3d(x-that.x, y-that.y, z-that.z)


  /** The product of a scalar value with all components of this vector. */ 
  def * (scalar: Double): Vector3d = Vector3d(x*scalar, y*scalar, z*scalar)

  /** The componentwise multiplication of this vector with another vector. */ 
  def * (that: Vector3d): Vector3d = Vector3d(x*that.x, y*that.y, z*that.z)


  /** The quotient of dividing all components of this vector by a scalar value. */ 
  def / (scalar: Double): Vector3d = Vector3d(x/scalar, y/scalar, z/scalar)

  /** The component-wise division of this vector by another vector. */ 
  def / (that: Vector3d): Vector3d = Vector3d(x/that.x, y/that.y, z/that.z)


  /** The dot-product of this and another vector. */
  def dot(that: Vector3d): Double = 
    x*that.x + y*that.y + z*that.z

  /** The cross-product of this and another vector. */
  def cross(that: Vector3d): Vector3d = 
    Vector3d(y * that.z - z * that.y,					    
             z * that.x - x * that.z,				    
             x * that.y - y * that.x)
  

  //------------------------------------------------------------------------------------------------
  //   C O M P A R I S O N                                                                  
  //------------------------------------------------------------------------------------------------

  /** Compares this vector to the specified value for equality. */
  override def equals(that: Any): Boolean = 
    that match {
      case that: Vector3d => 
        (that canEqual this) && (x == that.x) && (y == that.y) && (z == that.z)
      case _ => false
    }

  /** A method that should be called from every well-designed equals method that is open
    * to be overridden in a subclass. */
  def canEqual(that: Any): Boolean = 
    that.isInstanceOf[Vector3d]

  /** Returns a hash code value for the object. */
  override def hashCode: Int = 
    47 * (43 * (41 + x.##) + y.##) + z.##


  //------------------------------------------------------------------------------------------------
  //   U T I L I T Y                                                                        
  //------------------------------------------------------------------------------------------------

  /** Tests whether the given predicate holds true for all of the corresponding components
    * of this and the given vector. */ 
  def forall(that: Vector3d)(p: (Double, Double) => Boolean): Boolean = 
    p(x, that.x) && p(y, that.y) && p(z, that.z)

  /** Tests whether the given predicate holds true for any of the corresponding components
    * of this and the given vector. */ 
  def forany(that: Vector3d)(p: (Double, Double) => Boolean): Boolean = 
    p(x, that.x) || p(y, that.y) || p(z, that.z)

  /** Builds a new vector by applying a function to each component of this vector. */
  def map(f: (Double) => Double): Vector3d = 
    Vector3d(f(x), f(y), f(z))


  //------------------------------------------------------------------------------------------------
  //   C O N V E R S I O N                                                                  
  //------------------------------------------------------------------------------------------------

  /** Convert to a string representation. */
  override def toString() = 
    "Vector3d(%.2f, %.2f, %.2f)".format(x, y, z)

}

